- name: ping the server
  hosts: web      #which hosts your ansible server wants to connect with
  tasks: #lists of task to be performed/collections
  - name: ping the server
    ansible.builtin.ping:



