- name: PLAY-01
  hosts: web
  tasks: #list of tasks
  - name: PLAY-01 TASKS-01
    ansible.builtin.debug:
      msg: "This is from PLAY-01 TASK-01"

#PLAY-2
- name: PLAY-02
  hosts: web
  tasks: 
  - name: PLAY-02 TASK-02
    ansible.builtin.debug:
      msg: "This is from PLAY-02 TASK-02"

#PLAY-03

- name: PLAY-03
  hosts: web
  tasks: #list of tasks
  - name: PLAY-03 TASK-03
    ansible.builtin.debug:
      msg: "This is from PLAY-03 TASK-03"
