- name: install nginx and run
  hosts: web #list of nodes ansible server connecting with
  become: yes
  tasks:  #list of tasks to be performed
  - name: install nginx
    ansible.builtin.package:     #module-package --> heterogenous
      name: nginx                #package name, mandatory parameter
      state: present             #state: present -to install , mandatory
  - name: run nginx
    ansible.builtin.service:   #module-service 
      name: nginx              #service name, parameter: mandatory
      state: started           #state mandatory parameter values:started, stopped, restarted, rebooted
      enabled: yes