- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops With AWS"
    TRAINER: "Siva Kumar"
    DURATION: "120 Hours"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Hi, I'm Learning {{COURSE}}, from trainer:{{TRAINER}}, duration:{{DURATION}}"

